version: '3.8'

services:

  frontend:
    image: frontend-project-changed
    build: ./frontend-project
    ports:
      - 5001:5000
  backend:
    image: backend-project
    build: ./backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: db
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
      - ./nginx_file/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database:

    